apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pubsub
  namespace: burst
spec:
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - external:
      metric:
       name: pubsub.googleapis.com|subscription|num_undelivered_messages
       selector:
         matchLabels:
           resource.labels.subscription_id: sub-one
      target:
        type: Value
        value: "2"
    type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: hpc-job-processor