apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpc-job-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpc-job-processor
  template:
    metadata:
      name: hpc-job-processor
      labels:
        app: hpc-job-processor
    spec:
      initContainers:
      - command:
          - "/bin/sh"
          - "-c"
          - "touch /hpc/${NODE_NAME}_${HOSTNAME}"
        image: busybox
        name: init-container-msg-container-init
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - mountPath: /hpc
          name: fileserver
      containers:
      - name: hpc-job-processor
        image: us-east4-docker.pkg.dev/prj-gke-mt-spike/hpc-gke/hpc-job-processor-with-nfs:latest
        imagePullPolicy: Always
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - mountPath: /hpc
          name: fileserver
      nodeSelector:
        gpu: autoscale-to-zero
        iam.gke.io/gke-metadata-server-enabled: "true"
      tolerations:
      - key: reserved-pool
        operator: Equal
        value: "true"
        effect: NoSchedule
      volumes:
      - name: fileserver
        persistentVolumeClaim:
          claimName: fileserver