apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pubsub-100
  namespace: burst
spec:
  behavior:
    scaleUp:
      policies:
        - periodSeconds: 10
          type: Pods
          value: 4
    scaleDown:
      stabilizationWindowSeconds: 5
      policies:
      - type: Pods
        value: 5
        periodSeconds: 5
  minReplicas: 1
  maxReplicas: 16
  metrics:
  - external:
      metric:
       name: pubsub.googleapis.com|subscription|num_undelivered_messages
       selector:
         matchLabels:
           resource.labels.subscription_id: sub-one
      target:
        type: Value
        value: "100"
    type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: hpc-job-processor