apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer
spec:
  replicas: 2 # start with 2 replicas
  selector:
    matchLabels:
      app: writer
  template:
    metadata:
      labels:
        app: writer
    spec:
      initContainers:
      - command:
          - "/bin/sh"
          - "-c"
          - "touch /html/${NODE_NAME}_${HOSTNAME}"
        image: busybox
        name: init-container-msg-container-init
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - mountPath: /html
          name: fileserver
      containers:
      - name: content
        image: busybox
        volumeMounts:
        - name: fileserver
          mountPath: /html # the shared directory
        command: ["/bin/sh", "-c"]
        args:
        - cp /htmlTemp/indexInfo.html /html/index.html;
          while true; do
          cat /html/${HOSTNAME};
          sleep 30;  
          done
      nodeSelector:
        gpu: autoscale-to-zero
        iam.gke.io/gke-metadata-server-enabled: "true"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - hpc-job-processor
            topologyKey: "kubernetes.io/hostname"
      tolerations:
      - key: reserved-pool
        operator: Equal
        value: "true"
        effect: NoSchedule
      volumes:
      - name: fileserver
        persistentVolumeClaim:
          claimName: fileserver